### PR TITLE
Update input.js

### PR DESCRIPTION
**Pull request by dugi007**
Added remote source json/server query for autocomplete. Posible multidimensional arrays as response like  http://easyautocomplete.com/

im new to github sorry if i messed something up!

### CODE REVIEW

**Review by olton — CHANGES_REQUESTED** [review]
`_autocompleteUrlData: null` this can not be in the config object. This must be an internal field, defined in the `init` method with `_super` in the second argument.

**Comment by dugi007** [comment]
got it! changed!

**Comment by olton** [comment]
what the `o.autoCompleteUrlData`  in https://github.com/dugi007/Metro-UI-CSS/blob/patch-1/source/components/input/input.js#L362 ?

**Comment by olton** [comment]
Local data is always more important than remote data. In other words, the condition is wrong https://github.com/dugi007/Metro-UI-CSS/blob/patch-1/source/components/input/input.js#L358.

**Comment by olton** [comment]
Sorry, too many claims, please fix these and create a new pull request.

**Comment by dugi007** [comment]
o.autoCompleteUrlData is stored data after first ajax request if autocompleteUrlQuery set to false. If set to true, asks server for new data with new search after each keypress.

**Comment by olton** [comment]
> o.autoCompleteUrlData is stored data after first ajax request if autocompleteUrlQuery set to false. If set to true, asks server for new data with new search after each keypress.

The options contain only configuration parameters, everything else is in the internal fields defined in the init method!

**Pull request closed without merging**
