### PR TITLE
Update the appbar and Chinese localization files

### PR DESCRIPTION
**Pull request by tianxiaode**

### CODE REVIEW

**Comment by olton** [comment]
```
var container = element.find('.container');
if(container) element = container;
```
what is the purpose of this code?

**Comment by tianxiaode** [comment]
Query whether the container element is contained under the appbar element, and if so, add the element under the container element, not directly under the appbar element, in order to ensure that the menu action area is on its parent element.

从 Windows 版邮件发送

发件人: Serhii Pimenov
发送时间: 2023年2月27日 19:26
收件人: olton/Metro-UI-CSS
抄送: Dengqiao Huang; Author
主题: Re: [olton/Metro-UI-CSS] Update the appbar and Chinese localizationfiles (PR #1896)

var container = element.find('.container');
if(container) element = container;
what is the purpose of this code?

**Comment by olton** [comment]
I don't quite understand why this is. Could you do a demo for it on codepen.io?

**Comment by tianxiaode** [comment]
For example, the code for the sample file:

    <div data-role="appbar" data-expand-point="md">
        <div class="container  d-flex">
            <a href="#" class="brand no-hover mr-auto">
                <span style="width: 55px;">M4</span>
            </a>
            <ul class="app-bar-menu place-right">
                <li><a href="#">Home</a></li>
                <li>
                    <a href="#" class="dropdown-toggle">Products</a>
                    <ul class="d-menu" data-role="dropdown">
                        <li><a href="#">Windows 10</a></li>
                        <li><a href="#">Office 365</a></li>
                        <li class="divider bg-lightGray"></li>
                        <li><a href="#">Skype</a></li>
                    </ul>
                </li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Contacts</a></li>
            </ul>
        </div>
    </div>

A container is added to limit the display of the brand and menu, and after the component is initialized, the button will be added in the appbar, and many containers will be added, causing problems with the mobile menu.



The purpose of the added code is to ensure that the added button is within the correct element.

Later, it was found that putting the appbar inside the container, rather than the other way around, solved the problem.

<div class="w-100 bg-dark fg-white py-1">
    <div class="container">
        <div data-role="appbar" class="bg-dark pos-relative" data-expand-point="md">
                @(await Component.InvokeAsync<MainNavbarBrandViewComponent>())
                <ul class="app-bar-menu">
                    @(await Component.InvokeAsync<MainNavbarMenuViewComponent>())
                    @(await Component.InvokeAsync<MainNavbarToolbarViewComponent>())
                </ul>
        </div>
    </div>
</div>



从 Windows 版邮件发送

发件人: Serhii Pimenov
发送时间: 2023年2月27日 20:08
收件人: olton/Metro-UI-CSS
抄送: Dengqiao Huang; Author
主题: Re: [olton/Metro-UI-CSS] Update the appbar and Chinese localizationfiles (PR #1896)

I don't quite understand why this is. Could you do a demo for it on codepen.io?

**Comment by olton** [comment]
If you redefine an element, you lose all parameters defined in the element's data-* attributes and make it impossible to reuse them. It is better to immediately do the "correct markup".

**Comment by tianxiaode** [comment]
That's right, so this amendment can be ignored.

In fact, I am more interested in how to enhance the functionality of the table, so that when using the theme, there is no need to use other table libraries, so I am very looking forward to version 5.

从 Windows 版邮件发送

发件人: Serhii Pimenov
发送时间: 2023年2月27日 21:07
收件人: olton/Metro-UI-CSS
抄送: Dengqiao Huang; Author
主题: Re: [olton/Metro-UI-CSS] Update the appbar and Chinese localizationfiles (PR #1896)

If you redefine an element, you lose all parameters defined in the element's data-* attributes and make it impossible to reuse them. It is better to immediately do the "correct markup".

**Pull request merged**
