### PR TITLE
Update input.js try 2

### PR DESCRIPTION
**Pull request by dugi007**
Added remote source json/server query for autocomplete. Merged results from local and remote data. Posible multidimensional arrays as response like http://easyautocomplete.com/

### CODE REVIEW

**Review by olton — COMMENTED** [review]
why the `o.autocompleteUrlQuery` option is needed?

**Comment by dugi007** [comment]
in case of large amount of data to pass querying/filtering to server side. if set to true, it will request new data from server side with query string "q" with search term on each keypress..

**Comment by olton** [comment]
> in case of large amount of data to pass querying/filtering to server side. if set to true, it will request new data from server side with query string "q" with search term on each keypress..

1) I didn't find this implementation in your code for the quoted text above.
3) The dataset for autocomplete can be returned from the server as plain text, where each new sentence placed on a new line (user wishes)
2) Please give me a link to a working test
3) Your code not formated, with additional tabs!

**Comment by olton** [comment]
Please sign [CLA](https://github.com/olton/Metro-UI-CSS/blob/4.4.3/CLA.txt) and send the screenshot to email. Thank you.

**Comment by olton** [comment]
Data for autocomplete should be obtained at the stage of component creation and placed in the autocomplete field. The event `Metro.events.input` can't be modified. This event works only with the field `autocomplete`.

**Comment by olton** [comment]
I understood your idea and am implementing it today within the framework of the requirements I have expressed. Expect implementation. Thanks.

**Pull request closed without merging**
