### PR TITLE
fixed jquery strict function call using $

### PR DESCRIPTION
**Pull request by christopherreay**

### CODE REVIEW

**Comment by olton** [comment]
Hi. Thanks, but it's not actual, because in 3.0.8 all modules going through Grunt In one file, and automatically adds a special header, including support for AMD

**Comment by christopherreay** [comment]
Causes an error in my browser.

Thanks for replying

Any chance you can help me work out why I am getting <p> tags being created
which are destroying the layout of my tiles? Im trying to work out how to
put an <a> tag inside a tile. I dont think Im doing it right.

http://pastebin.com/Zp2GcmfV

I cant find an example of how to do this on the website
Thanks!



On 22 July 2015 at 16:03, Sergey Pimenov <notifications@github.com> wrote:

> Hi. Thanks, but it's not actual, because in 3.0.8 all modules going
> through Grunt In one file, and automatically adds a special header,
> including support for AMD
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olton/Metro-UI-CSS/pull/779#issuecomment-123751510>.
>



-- 

Be prepared to have your predictions come true

**Comment by christopherreay** [comment]
Im trying the develop branch

**Comment by olton** [comment]
All tiles has float left.

**Pull request closed without merging**
