### PR TITLE
Various Fixes and Improvements

### PR DESCRIPTION
**Pull request by kens-code**
improve/fix clock plugin

### CODE REVIEW

**Comment by kens-code** [comment]
Commit 8f9ea7a

- Added leadingZero, dateDivider and timeDivider options to the clock plugin.
- Changed the timeFormat check from a string to a number as o.timeFormat is typeof number.
- Added the clock-suffix span element as it was missing from prior build.

**Comment by kens-code** [comment]
Commit e21e17b

- Added the ability to choose whether or not to show the about message via the console.log() function during Metro.init()
- This value can be set via a meta tag or the window.METRO_SHOW_ABOUT variable.
- The default value is set to true.

**Comment by kens-code** [comment]
Commit 82992c2

- Improved the Touch functionality of the start, stop, move and enter events.
Currently, if a touch device is detected, those events will not fire for the mouse.
We should not assume that if a user has a touch device such as a touch screen laptop, that they do not want to use their mouse.
- Improved detection of touch device by adding one time Event Listener on touchstart to set the variables isTouch and Metro.isTouchable once a touch has been detected as the following code below is not always 100% reliable.
_(('ontouchstart' in window) || (navigator.MaxTouchPoints > 0) || (navigator.msMaxTouchPoints > 0))_

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/blob/master/CONTRIBUTING.md#pull-request-guidelines

### Each pull request should close one problem.

**Comment by olton** [comment]
For:
```
 start: isTouch ? 'touchstart.metro' : 'mousedown.metro',
 stop: isTouch ? 'touchend.metro' : 'mouseup.metro',
 move: isTouch ? 'touchmove.metro' : 'mousemove.metro',
 enter: isTouch ? 'touchstart.metro' : 'mouseenter.metro',
```
I specifically did this because otherwise, the spinner on the Android and in Chrome does not work correctly. Event firing twice and can't be canceled.

**Comment by olton** [comment]
https://github.com/olton/Metro-UI-CSS/blob/4.2.40/js/metro.js#L25

**Pull request closed without merging**
